// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CognitoSyncGenerator.Templates.SourceFiles
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\AssemblyInfo.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class AssemblyInfo : BaseGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Reflection;\r\nusing System.Runtime.InteropServices;\r\nu" +
                    "sing System.Runtime.CompilerServices;\r\n\r\n[assembly: AssemblyTitle(\"AWSSDK.SyncMa" +
                    "nager\")]\r\n#if BCL35\r\n[assembly: AssemblyDescription(\"The Amazon Web Services SDK" +
                    " for .NET (3.5) - Amazon Cognito Sync. Amazon Cognito is a service that makes it" +
                    " easy to save user data, such as app preferences or game state, in the AWS Cloud" +
                    " without writing any backend code or managing any infrastructure. With Amazon Co" +
                    "gnito, you can focus on creating great app experiences instead of having to worr" +
                    "y about building and managing a backend solution to handle identity management, " +
                    "network state, storage, and sync.\")]\r\n#elif BCL45\r\n[assembly: AssemblyDescriptio" +
                    "n(\"The Amazon Web Services SDK for .NET (4.5) - Amazon Cognito Sync. Amazon Cogn" +
                    "ito is a service that makes it easy to save user data, such as app preferences o" +
                    "r game state, in the AWS Cloud without writing any backend code or managing any " +
                    "infrastructure. With Amazon Cognito, you can focus on creating great app experie" +
                    "nces instead of having to worry about building and managing a backend solution t" +
                    "o handle identity management, network state, storage, and sync.\")]\r\n#elif PCL\r\n[" +
                    "assembly: AssemblyDescription(\"The Amazon Web Services SDK for .NET (PCL)-  Amaz" +
                    "on Cognito Sync. Amazon Cognito is a service that makes it easy to save user dat" +
                    "a, such as app preferences or game state, in the AWS Cloud without writing any b" +
                    "ackend code or managing any infrastructure. With Amazon Cognito, you can focus o" +
                    "n creating great app experiences instead of having to worry about building and m" +
                    "anaging a backend solution to handle identity management, network state, storage" +
                    ", and sync.\")]\r\n#else\r\n#error Unknown platform constant - unable to set correct " +
                    "AssemblyDescription\r\n#endif\r\n\r\n[assembly: AssemblyConfiguration(\"\")]\r\n[assembly:" +
                    " AssemblyProduct(\"Amazon Web Services SDK for .NET\")]\r\n[assembly: AssemblyCompan" +
                    "y(\"Amazon.com, Inc\")]\r\n[assembly: AssemblyCopyright(\"Copyright 2009-");
            
            #line 25 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\AssemblyInfo.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.UtcNow.Year));
            
            #line default
            #line hidden
            this.Write(@" Amazon.com, Inc. or its affiliates. All Rights Reserved."")]
[assembly: AssemblyTrademark("""")]
[assembly: AssemblyCulture("""")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion(""1.0.*"")]
[assembly: AssemblyVersion(""");
            
            #line 44 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\AssemblyInfo.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.ServiceVersion));
            
            #line default
            #line hidden
            this.Write("\")]\r\n[assembly: AssemblyFileVersion(\"");
            
            #line 45 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\AssemblyInfo.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Version));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\r\n#if WINDOWS_PHONE\r\n[assembly: System.CLSCompliant(false)]\r\n# else\r\n[assemb" +
                    "ly: System.CLSCompliant(true)]\r\n#endif\r\n\r\n#if BCL\r\n[assembly: System.Security.Al" +
                    "lowPartiallyTrustedCallers()]\r\n#endif");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
