// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CognitoSyncGenerator.Templates.SourceFiles
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class NuSpec : BaseGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<package> \r\n  <metadata> \r\n    <id>AWSSDK" +
                    ".SyncManager</id>\r\n    <title>AWSSDK - Amazon Cognito Sync Manager</title>\r\n    " +
                    "<version>");
            
            #line 11 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Version));
            
            #line default
            #line hidden
            
            #line 11 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.InPreview?"-preview":""));
            
            #line default
            #line hidden
            this.Write(@"</version> 
    <authors>Amazon Web Services</authors>
    <description>OBSOLETE - Please use AWSSDK.CognitoSync instead. Sync Manager is now directly included in AWSSDK.CognitoSync. Amazon Cognito is a service that makes it easy to save user data, such as app preferences or game state, in the AWS Cloud without writing any backend code or managing any infrastructure.</description> 
    <language>en-US</language>
    <licenseUrl>http://aws.amazon.com/asl/</licenseUrl>    
    <projectUrl>https://github.com/aws/amazon-cognito-dotnet</projectUrl>
    <tags>AWS Amazon cloud CognitoSync</tags>
    <iconUrl>http://media.amazonwebservices.com/aws_singlebox_01.png</iconUrl>
	<requireLicenseAcceptance>true</requireLicenseAcceptance>
    <dependencies>
      <group targetFramework=""net45"">
");
            
            #line 22 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"

			foreach(var dependency in this.Config.Dependencies)
			{
				if(dependency.TestOnly)
					continue;

				if(dependency.Primary )
				{
					var verTokens = dependency.Version.Split('.');
					var versionRange = string.Format("[{0}{3}, {1}.{2}{3})", dependency.Version, verTokens[0], int.Parse(verTokens[1]) + 1, dependency.InPreview?PreviewFlag:"");

            
            #line default
            #line hidden
            this.Write("\t\t<dependency id=\"");
            
            #line 33 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 33 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Name));
            
            #line default
            #line hidden
            this.Write("\" version=\"");
            
            #line 33 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(versionRange));
            
            #line default
            #line hidden
            this.Write("\" />\r\n");
            
            #line 34 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"

				}
			}

            
            #line default
            #line hidden
            this.Write("      </group>\r\n\t  <group targetFramework=\"portable-net45+netcore45+wpa81+wp8+Mon" +
                    "oAndroid10+xamarinios10\">\r\n");
            
            #line 40 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"

			foreach(var dependency in this.Config.Dependencies)
			{
				if(dependency.Primary)
				{
					var verTokens = dependency.Version.Split('.');
					var versionRange = string.Format("[{0}{3}, {1}.{2}{3})", dependency.Version, verTokens[0], int.Parse(verTokens[1]) + 1, dependency.InPreview?PreviewFlag:"");

            
            #line default
            #line hidden
            this.Write("\t\t<dependency id=\"");
            
            #line 48 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 48 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Name));
            
            #line default
            #line hidden
            this.Write("\" version=\"");
            
            #line 48 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(versionRange));
            
            #line default
            #line hidden
            this.Write("\" />\r\n");
            
            #line 49 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\NuSpec.tt"

				}
			}

            
            #line default
            #line hidden
            this.Write("\t  </group>\r\n    </dependencies>\r\n  </metadata>\r\n  <files>\r\n  </files>\r\n</package" +
                    ">");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
