// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CognitoSyncGenerator.Templates.SourceFiles
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class PackagesConfig : BaseGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<packages>\r\n");
            
            #line 8 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"

			foreach(var dependency in this.Config.Dependencies)
			{
				if(dependency.TestOnly)
					continue;

            
            #line default
            #line hidden
            this.Write("  <package id=\"");
            
            #line 14 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 14 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Name));
            
            #line default
            #line hidden
            this.Write("\" version=\"");
            
            #line 14 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Version));
            
            #line default
            #line hidden
            
            #line 14 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\" targetFramework=\"portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoT" +
                    "ouch10\" />\r\n");
            
            #line 15 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"

			}

            
            #line default
            #line hidden
            this.Write("  <package id=\"EntityFramework\" version=\"6.0.0\" targetFramework=\"net45\" requireRe" +
                    "installation=\"True\" />\r\n  <package id=\"Microsoft.Bcl\" version=\"1.1.10\" targetFra" +
                    "mework=\"portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10\" />" +
                    "\r\n  <package id=\"Microsoft.Bcl.Build\" version=\"1.0.14\" targetFramework=\"portable" +
                    "-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10\" />\r\n  <package id=" +
                    "\"Microsoft.Net.Http\" version=\"2.2.29\" targetFramework=\"portable-net45+win+wpa81+" +
                    "wp80+MonoAndroid10+xamarinios10+MonoTouch10\" />\r\n  <package id=\"Mono.Security\" v" +
                    "ersion=\"3.2.3.0\" targetFramework=\"net45\" requireReinstallation=\"True\" />\r\n  <pac" +
                    "kage id=\"PCLCrypto\" version=\"1.0.2.15130\" targetFramework=\"portable-net45+win+wp" +
                    "a81+wp80+MonoAndroid10+xamarinios10+MonoTouch10\" />\r\n  <package id=\"PCLStorage\" " +
                    "version=\"1.0.2\" targetFramework=\"portable-net45+win+wpa81+wp80+MonoAndroid10+xam" +
                    "arinios10+MonoTouch10\" />\r\n  <package id=\"SQLitePCL\" version=\"3.8.7.2\" targetFra" +
                    "mework=\"portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10\" />" +
                    "\r\n  <package id=\"System.Data.SQLite\" version=\"1.0.97.0\" targetFramework=\"net45\" " +
                    "/>\r\n  <package id=\"System.Data.SQLite.Core\" version=\"1.0.97.0\" targetFramework=\"" +
                    "net45\" requireReinstallation=\"True\" />\r\n  <package id=\"System.Data.SQLite.EF6\" v" +
                    "ersion=\"1.0.97.0\" targetFramework=\"net45\" requireReinstallation=\"True\" />\r\n  <pa" +
                    "ckage id=\"System.Data.SQLite.Linq\" version=\"1.0.97.0\" targetFramework=\"net45\" re" +
                    "quireReinstallation=\"True\" />\r\n  <package id=\"Validation\" version=\"2.0.6.15003\" " +
                    "targetFramework=\"portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTo" +
                    "uch10\" />\r\n</packages>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
