// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CognitoSyncGenerator.Templates.SourceFiles
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class PackagesConfig : BaseGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<packages>\r\n");
            
            #line 8 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"

			foreach(var dependency in this.Config.Dependencies)
			{
				if(dependency.TestOnly)
					continue;

            
            #line default
            #line hidden
            this.Write("  <package id=\"");
            
            #line 14 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 14 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Name));
            
            #line default
            #line hidden
            this.Write("\" version=\"");
            
            #line 14 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Version));
            
            #line default
            #line hidden
            
            #line 14 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\" targetFramework=\"portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoT" +
                    "ouch10\" />\r\n");
            
            #line 15 "C:\a\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\SourceFiles\PackagesConfig.tt"

			}

            
            #line default
            #line hidden
            this.Write("</packages>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
