// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CognitoSyncGenerator.Templates.Component
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class Component : BaseGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"%YAML 1.2
---
summary: AWS CognitoSync SDK for Xamarin
getting-started: GettingStarted.md
details: Details.md
license: ..\License.md
icons: 
  - ..\awsmobile_128.png
  - ..\awsmobile_512.png
publisher: Amazon Web Services
name: AWSSDK - Amazon Cognito Sync
id: aws-cognitosync-sdk
samples: 
  - name: ""CognitoSync-Sample""
    path: ""..\\..\\sample\\TODOList\\TODOList.sln""
publisher-url: http://aws.amazon.com/mobile/sdk/
packages:
  android:
");
            
            #line 24 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"

			foreach(var dependency in this.Config.Dependencies)
			{
				if(dependency.TestOnly)
					continue;

            
            #line default
            #line hidden
            this.Write("  - ");
            
            #line 30 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 30 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Name));
            
            #line default
            #line hidden
            this.Write(", Version=");
            
            #line 30 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Version));
            
            #line default
            #line hidden
            
            #line 30 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 31 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"

			}

            
            #line default
            #line hidden
            this.Write("  - ");
            
            #line 34 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 34 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.AssemblyName));
            
            #line default
            #line hidden
            this.Write(",Version=");
            
            #line 34 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Version));
            
            #line default
            #line hidden
            
            #line 34 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\r\n  ios-unified:\r\n");
            
            #line 36 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"

			foreach(var dependency in this.Config.Dependencies)
			{
				if(dependency.TestOnly)
					continue;

            
            #line default
            #line hidden
            this.Write("  - ");
            
            #line 42 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 42 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Name));
            
            #line default
            #line hidden
            this.Write(", Version=");
            
            #line 42 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Version));
            
            #line default
            #line hidden
            
            #line 42 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"

			}

            
            #line default
            #line hidden
            this.Write("  - ");
            
            #line 46 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 46 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.AssemblyName));
            
            #line default
            #line hidden
            this.Write(",Version=");
            
            #line 46 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Version));
            
            #line default
            #line hidden
            
            #line 46 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\r\n  winphone-8.0:\r\n");
            
            #line 48 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"

			foreach(var dependency in this.Config.Dependencies)
			{
				if(dependency.TestOnly)
					continue;

            
            #line default
            #line hidden
            this.Write("  - ");
            
            #line 54 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 54 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Name));
            
            #line default
            #line hidden
            this.Write(", Version=");
            
            #line 54 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Version));
            
            #line default
            #line hidden
            
            #line 54 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 55 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"

			}

            
            #line default
            #line hidden
            this.Write("  - ");
            
            #line 58 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 58 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.AssemblyName));
            
            #line default
            #line hidden
            this.Write(",Version=");
            
            #line 58 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Version));
            
            #line default
            #line hidden
            
            #line 58 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\r\n  winphone-8.1:\r\n");
            
            #line 60 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"

			foreach(var dependency in this.Config.Dependencies)
			{
				if(dependency.TestOnly)
					continue;

            
            #line default
            #line hidden
            this.Write("  - ");
            
            #line 66 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 66 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Name));
            
            #line default
            #line hidden
            this.Write(", Version=");
            
            #line 66 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Version));
            
            #line default
            #line hidden
            
            #line 66 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 67 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"

			}

            
            #line default
            #line hidden
            this.Write("  - ");
            
            #line 70 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 70 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.AssemblyName));
            
            #line default
            #line hidden
            this.Write(",Version=");
            
            #line 70 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Version));
            
            #line default
            #line hidden
            
            #line 70 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 71 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"

//component doesnot support preview flags like nuget, so we dont add that

            
            #line default
            #line hidden
            this.Write("version: ");
            
            #line 74 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\Component.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Version));
            
            #line default
            #line hidden
            this.Write("\r\nis-shell: true\r\n...");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
