// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CognitoSyncGenerator.Templates.Component
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\Component\GettingStarted.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class GettingStarted : BaseGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nIf you’re new to the AWS SDK for .Net/Xamarin, you’ll probably want to look fir" +
                    "st at [Getting Started with the AWS SDK for .NET/Xamarin](http://docs.aws.amazon" +
                    ".com/mobile/sdkforxamarin/developerguide/) which explains how to set up the SDK " +
                    "and how to get started using AWS Cognito Sync Services from an Xamarin applicati" +
                    "on.\r\n\r\nAfter you’ve set up the SDK, you can start working with the mobile client" +
                    "s for Amazon Web Services. The mobile clients are described in the service-speci" +
                    "fic topics. No matter which services you’re using, you should provide AWS creden" +
                    "tials to your app via Amazon Cognito. The Amazon Cognito credentials provider is" +
                    " discussed briefly in the various mobile service topics, and at length in the [A" +
                    "mazon Cognito Developer Guide](http://docs.aws.amazon.com/cognito/devguide/).\r\n\r" +
                    "\n<h2>Additional Resources</h2>\r\n\r\n<ul>\r\n<li>\r\n<a href=\"http://docs.aws.amazon.co" +
                    "m/mobile/sdkforxamarin/developerguide/\"><b>Xamarin Developer Guide</b></a> - For" +
                    " in-depth getting started and usage information\r\n</li>\r\n<li>\r\n<a href=\"https://g" +
                    "ithub.com/awslabs/aws-sdk-net-samples\"><b>Code Sample</b></a> - Repository of ex" +
                    "ample projects using the SDK.\r\n</li>\r\n<li>\r\n<a href=\"https://forums.aws.amazon.c" +
                    "om/forum.jspa?forumID=88\"><b>AWS Mobile Forum</b></a> – Ask questions, get help," +
                    " and give feedback\r\n</li>\r\n<li>\r\n<a href=\"http://docs.aws.amazon.com/sdkfornet/l" +
                    "atest/apidocs/Index.html\"><b>API Reference</b></a> - For operations, parameters," +
                    " responses, and examples\r\n</li>\r\n<li>\r\n<a href=\"http://mobile.awsblog.com/\"><b>A" +
                    "WS Mobile Developer Blog</b></a> - For updates and guidance on using the AWS SDK" +
                    " for Xamarin\r\n</li>\r\n<li>\r\n<a href=\"https://aws.amazon.com/releasenotes/.NET\"><b" +
                    ">Release Notes</b></a> - To see the latest features, bug fixes, and changes in t" +
                    "he SDK\r\n</li>\r\n<li>\r\n<a href=\"https://github.com/aws/aws-sdk-net/issues\"><b>Issu" +
                    "es</b></a>  - Report issues and submit pull requests\r\n</li>\r\n<li>\r\n<a href=\"http" +
                    "s://twitter.com/awsformobile\"><b>@awsformobile</b></a> - Follow us on Twitter\r\n<" +
                    "/li>\r\n</ul>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
