// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CognitoSyncGenerator.Templates.ProjectFiles
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class PCLProjectTemplate : BaseGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Project ToolsVersion=\"12.0\" DefaultTarge" +
                    "ts=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\r\n  <Impo" +
                    "rt Project=\"$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.pro" +
                    "ps\" Condition=\"Exists(\'$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft" +
                    ".Common.props\')\" />\r\n  <PropertyGroup>\r\n    <MinimumVisualStudioVersion>10.0</Mi" +
                    "nimumVisualStudioVersion>\r\n    <Configuration Condition=\" \'$(Configuration)\' == " +
                    "\'\' \">Debug</Configuration>\r\n    <Platform Condition=\" \'$(Platform)\' == \'\' \">AnyC" +
                    "PU</Platform>\r\n    <ProjectGuid>{D8590BBA-340E-4368-A96A-E5298FA40BCA}</ProjectG" +
                    "uid>\r\n    <OutputType>Library</OutputType>\r\n    <AppDesignerFolder>Properties</A" +
                    "ppDesignerFolder>\r\n    <RootNamespace>Amazon.CognitoSync.SyncManager</RootNamesp" +
                    "ace>\r\n    <AssemblyName>AWSSDK.SyncManager</AssemblyName>\r\n    <DefaultLanguage>" +
                    "en-US</DefaultLanguage>\r\n    <FileAlignment>512</FileAlignment>\r\n    <ProjectTyp" +
                    "eGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79E" +
                    "FBC}</ProjectTypeGuids>\r\n    <TargetFrameworkProfile>Profile259</TargetFramework" +
                    "Profile>\r\n    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>\r\n    <Soluti" +
                    "onDir Condition=\"$(SolutionDir) == \'\' Or $(SolutionDir) == \'*Undefined*\'\">..\\</S" +
                    "olutionDir>\r\n    <BaseIntermediateOutputPath>obj\\pcl</BaseIntermediateOutputPath" +
                    ">\r\n    <RestorePackages>true</RestorePackages>\r\n    <NuGetPackageImportStamp>9a5" +
                    "790a0</NuGetPackageImportStamp>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=" +
                    "\" \'$(Configuration)|$(Platform)\' == \'Debug|AnyCPU\' \">\r\n    <DebugSymbols>true</D" +
                    "ebugSymbols>\r\n    <DebugType>full</DebugType>\r\n    <Optimize>false</Optimize>\r\n " +
                    "   <OutputPath>bin\\Debug\\pcl</OutputPath>\r\n    <DefineConstants>TRACE;DEBUG;PCL;" +
                    "AWS_ASYNC_API;LOCAL_FILE;</DefineConstants>\r\n    <ErrorReport>prompt</ErrorRepor" +
                    "t>\r\n    <WarningLevel>4</WarningLevel>\r\n    <DocumentationFile>bin\\Debug\\pcl\\AWS" +
                    "SDK.SyncManager.xml</DocumentationFile>\r\n  </PropertyGroup>\r\n  <PropertyGroup Co" +
                    "ndition=\" \'$(Configuration)|$(Platform)\' == \'Release|AnyCPU\' \">\r\n    <DebugType>" +
                    "pdbonly</DebugType>\r\n    <Optimize>true</Optimize>\r\n    <OutputPath>bin\\Release\\" +
                    "pcl</OutputPath>\r\n    <DefineConstants>TRACE;;PCL;AWS_ASYNC_API;LOCAL_FILE</Defi" +
                    "neConstants>\r\n    <ErrorReport>prompt</ErrorReport>\r\n    <WarningLevel>4</Warnin" +
                    "gLevel>\r\n    <DocumentationFile>bin\\Release\\pcl\\AWSSDK.SyncManager.XML</Document" +
                    "ationFile>\r\n  </PropertyGroup>\r\n  <PropertyGroup>\r\n    <SignAssembly>true</SignA" +
                    "ssembly>\r\n  </PropertyGroup>\r\n  <Choose>\r\n    <When Condition=\" \'$(AWSKeyFile)\' " +
                    "== \'\' \">\r\n      <PropertyGroup>\r\n        <AssemblyOriginatorKeyFile>..\\awssdk.dl" +
                    "l.snk</AssemblyOriginatorKeyFile>\r\n      </PropertyGroup>\r\n    </When>\r\n    <Oth" +
                    "erwise>\r\n      <PropertyGroup>\r\n        <AssemblyOriginatorKeyFile>$(AWSKeyFile)" +
                    "</AssemblyOriginatorKeyFile>\r\n      </PropertyGroup>\r\n    </Otherwise>\r\n  </Choo" +
                    "se>\r\n  <ItemGroup>\r\n    <Compile Include=\"Properties\\AssemblyInfo.cs\" />\r\n    <C" +
                    "ompile Include=\"SyncManager\\*.cs\">\r\n      <SubType>Code</SubType>\r\n    </Compile" +
                    ">\r\n    <Compile Include=\"SyncManager\\_pcl\\*.cs\">\r\n      <SubType>Code</SubType>\r" +
                    "\n    </Compile>\r\n    <Compile Include=\"SyncManager\\Exceptions\\*.cs\">\r\n      <Sub" +
                    "Type>Code</SubType>\r\n    </Compile>\r\n    <Compile Include=\"SyncManager\\Model\\*.c" +
                    "s\">\r\n      <SubType>Code</SubType>\r\n    </Compile>\r\n    <Compile Include=\"SyncMa" +
                    "nager\\Storage\\*.cs\">\r\n      <SubType>Code</SubType>\r\n    </Compile>\r\n    <Compil" +
                    "e Include=\"SyncManager\\Storage\\_pcl\\*.cs\">\r\n      <SubType>Code</SubType>\r\n    <" +
                    "/Compile>\r\n    <Compile Include=\"SyncManager\\Util\\*.cs\">\r\n      <SubType>Code</S" +
                    "ubType>\r\n    </Compile>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n");
            
            #line 87 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"

			foreach(var dependency in this.Config.Dependencies)
			{
				if(dependency.TestOnly)
					continue;

            
            #line default
            #line hidden
            this.Write("    <Reference Include=\"");
            
            #line 93 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 93 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Name));
            
            #line default
            #line hidden
            this.Write("\">\r\n      <HintPath>");
            
            #line 94 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.PackagesPath));
            
            #line default
            #line hidden
            this.Write("\\");
            
            #line 94 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Prefix));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 94 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 94 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Version));
            
            #line default
            #line hidden
            
            #line 94 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.InPreview?PreviewFlag:""));
            
            #line default
            #line hidden
            this.Write("\\");
            
            #line 94 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.ReferencePaths["PCL"]));
            
            #line default
            #line hidden
            this.Write("</HintPath>\r\n      <Private>True</Private>\r\n    </Reference>\r\n");
            
            #line 97 "C:\dev\dotnet\AWSDotNetSyncManager\generator\CognitoSyncGenerator\Templates\ProjectFiles\PCLProjectTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("    <Reference Include=\"PCLCrypto, Version=1.0.0.0, Culture=neutral, PublicKeyTok" +
                    "en=d4421c8a4786956c, processorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\P" +
                    "CLCrypto.1.0.2.15130\\lib\\portable-net40+sl50+win+wpa81+wp80+MonoAndroid10+xamari" +
                    "nios10+MonoTouch10\\PCLCrypto.dll</HintPath>\r\n      <Private>True</Private>\r\n    " +
                    "</Reference>\r\n    <Reference Include=\"PCLStorage, Version=1.0.2.0, Culture=neutr" +
                    "al, PublicKeyToken=286fe515a2c35b64, processorArchitecture=MSIL\">\r\n      <HintPa" +
                    "th>..\\packages\\PCLStorage.1.0.2\\lib\\portable-net45+wp8+wpa81+win8+monoandroid+mo" +
                    "notouch+Xamarin.iOS+Xamarin.Mac\\PCLStorage.dll</HintPath>\r\n      <Private>True</" +
                    "Private>\r\n    </Reference>\r\n    <Reference Include=\"PCLStorage.Abstractions, Ver" +
                    "sion=1.0.2.0, Culture=neutral, PublicKeyToken=286fe515a2c35b64, processorArchite" +
                    "cture=MSIL\">\r\n      <HintPath>..\\packages\\PCLStorage.1.0.2\\lib\\portable-net45+wp" +
                    "8+wpa81+win8+monoandroid+monotouch+Xamarin.iOS+Xamarin.Mac\\PCLStorage.Abstractio" +
                    "ns.dll</HintPath>\r\n      <Private>True</Private>\r\n    </Reference>\r\n    <Referen" +
                    "ce Include=\"SQLitePCL, Version=3.8.7.2, Culture=neutral, PublicKeyToken=bddade01" +
                    "e9c850c5, processorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\SQLitePCL.3." +
                    "8.7.2\\lib\\portable-net45+sl50+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouc" +
                    "h10\\SQLitePCL.dll</HintPath>\r\n      <Private>True</Private>\r\n    </Reference>\r\n " +
                    "   <Reference Include=\"System\" />\r\n    <Reference Include=\"System.Core\" />\r\n    " +
                    "<Reference Include=\"System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKey" +
                    "Token=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n      <HintPath>..\\package" +
                    "s\\Microsoft.Net.Http.2.2.29\\lib\\portable-net40+sl4+win8+wp71+wpa81\\System.Net.Ht" +
                    "tp.dll</HintPath>\r\n      <Private>True</Private>\r\n    </Reference>\r\n    <Referen" +
                    "ce Include=\"System.Net.Http.Extensions, Version=1.5.0.0, Culture=neutral, Public" +
                    "KeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n      <HintPath>..\\pack" +
                    "ages\\Microsoft.Net.Http.2.2.29\\lib\\portable-net40+sl4+win8+wp71+wpa81\\System.Net" +
                    ".Http.Extensions.dll</HintPath>\r\n      <Private>True</Private>\r\n    </Reference>" +
                    "\r\n    <Reference Include=\"System.Net.Http.Primitives, Version=1.5.0.0, Culture=n" +
                    "eutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n      <Hi" +
                    "ntPath>..\\packages\\Microsoft.Net.Http.2.2.29\\lib\\portable-net40+sl4+win8+wp71+wp" +
                    "a81\\System.Net.Http.Primitives.dll</HintPath>\r\n      <Private>True</Private>\r\n  " +
                    "  </Reference>\r\n    <Reference Include=\"System.Xml.Linq\" />\r\n    <Reference Incl" +
                    "ude=\"System.Xml\" />\r\n    <Reference Include=\"Validation, Version=2.0.0.0, Cultur" +
                    "e=neutral, PublicKeyToken=2fc06f0d701809a7, processorArchitecture=MSIL\">\r\n      " +
                    "<HintPath>..\\packages\\Validation.2.0.6.15003\\lib\\portable-net40+sl50+win+wpa81+w" +
                    "p80+Xamarin.iOS10+MonoAndroid10+MonoTouch10\\Validation.dll</HintPath>\r\n      <Pr" +
                    "ivate>True</Private>\r\n    </Reference>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <None" +
                    " Include=\"packages.config\">\r\n      <SubType>Designer</SubType>\r\n    </None>\r\n  <" +
                    "/ItemGroup>\r\n  <Import Project=\"$(MSBuildExtensionsPath32)\\Microsoft\\Portable\\$(" +
                    "TargetFrameworkVersion)\\Microsoft.Portable.CSharp.targets\" />\r\n  <Import Project" +
                    "=\"$(SolutionDir)\\.nuget\\NuGet.targets\" Condition=\"Exists(\'$(SolutionDir)\\.nuget\\" +
                    "NuGet.targets\')\" />\r\n  <Target Name=\"EnsureNuGetPackageBuildImports\" BeforeTarge" +
                    "ts=\"PrepareForBuild\">\r\n    <PropertyGroup>\r\n      <ErrorText>This project refere" +
                    "nces NuGet package(s) that are missing on this computer. Enable NuGet Package Re" +
                    "store to download them.  For more information, see http://go.microsoft.com/fwlin" +
                    "k/?LinkID=322105. The missing file is {0}.</ErrorText>\r\n    </PropertyGroup>\r\n  " +
                    "  <Error Condition=\"!Exists(\'$(SolutionDir)\\.nuget\\NuGet.targets\')\" Text=\"$([Sys" +
                    "tem.String]::Format(\'$(ErrorText)\', \'$(SolutionDir)\\.nuget\\NuGet.targets\'))\" />\r" +
                    "\n  </Target>\r\n  <Import Project=\"..\\packages\\Microsoft.Bcl.Build.1.0.14\\tools\\Mi" +
                    "crosoft.Bcl.Build.targets\" Condition=\"Exists(\'..\\packages\\Microsoft.Bcl.Build.1." +
                    "0.14\\tools\\Microsoft.Bcl.Build.targets\')\" />\r\n  <Target Name=\"EnsureBclBuildImpo" +
                    "rted\" BeforeTargets=\"BeforeBuild\" Condition=\"\'$(BclBuildImported)\' == \'\'\">\r\n    " +
                    "<Error Condition=\"!Exists(\'..\\packages\\Microsoft.Bcl.Build.1.0.14\\tools\\Microsof" +
                    "t.Bcl.Build.targets\')\" Text=\"This project references NuGet package(s) that are m" +
                    "issing on this computer. Enable NuGet Package Restore to download them.  For mor" +
                    "e information, see http://go.microsoft.com/fwlink/?LinkID=317567.\" HelpKeyword=\"" +
                    "BCLBUILD2001\" />\r\n    <Error Condition=\"Exists(\'..\\packages\\Microsoft.Bcl.Build." +
                    "1.0.14\\tools\\Microsoft.Bcl.Build.targets\')\" Text=\"The build restored NuGet packa" +
                    "ges. Build the project again to include these packages in the build. For more in" +
                    "formation, see http://go.microsoft.com/fwlink/?LinkID=317568.\" HelpKeyword=\"BCLB" +
                    "UILD2002\" />\r\n  </Target>\r\n  <!-- To modify your build process, add your task in" +
                    "side one of the targets below and uncomment it. \r\n       Other similar extension" +
                    " points exist, see Microsoft.Common.targets.\r\n  <Target Name=\"BeforeBuild\">\r\n  <" +
                    "/Target>\r\n  <Target Name=\"AfterBuild\">\r\n  </Target>\r\n  -->\r\n</Project>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
